#!/usr/bin/ruby
require 'thor'

class BifrostCLI < Thor

  GIT_SHORTCUTS = {
    :co  => :checkout,
    :cm  => :commit,
    :b   => :branch, 
    :l   => :log,
    :r   => :reset,
    :s   => :status,
    :rb  => :rebase
  }

  desc "git_conf! <name> <email> <favourite-editor>", "Generate git globals configurations and shortcuts."
  option :only_stdout
  def git_conf!(name, email, editor)
    cmd_list = []
    GIT_SHORTCUTS.each do |sc, cmd|
      cmd_list << "git config --global alias.#{sc} #{cmd}"
    end
    cmd_list << "git config --global user.name #{name}"
    cmd_list << "git config --global user.email #{email}"
    cmd_list << "git config --global core.editor #{editor}"
    exec_cmds cmd_list unless options[:only_stdout]
    puts cmd_list
  end
  
  desc "vid2mp3 <files>", "Convert video to mp3 with ffmpeg"
  def vid2mp3(*files)
    cmd_list = []
    files.each do |f|
      cmd_list << "ffmpeg -i \"#{f}\" -vn \"#{f}.mp3\""
    end
    exec_cmds cmd_list unless only_stdout?
    puts cmd_list
  end

  desc "middleman article [--blog BLOGNAME(def. 'blog')] <article-title>", "Create new middleman article"
  option :blog
  def middleman(action, *args)
    blog = options[:blog] || "blog"
    if action == "article"
      title = args[0]
      `bundle exec middleman article -b #{blog} #{title}`
    else
      raise "No action defined: #{action}"
    end
  end

  desc "i3msg <action> <params>", "Wrapparound i3msg executable (http://i3wm.org)"
  def i3msg(action)
    puts `i3-msg mark #{action}`
    puts `i3-msg [con_mark="#{action}"] focus`
    puts `i3-msg unmark #{action}`   
  end  

  private

  def exec_cmds(cmds)
    cmds = [ cmds ] if cmds.is_a? String
    cmds.map { |cmd| `#{cmd}` }
  end
end

BifrostCLI.start ARGV
